version = 0.1

[default.deploy.parameters]
stack_name = "slideshow-api-fastapi"
resolve_s3 = true
s3_prefix = "slideshow-api-fastapi"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
